# Upstream: notify configured forks on every push to main via repository_dispatch
# Add this to the upstream repo (KadenLi6741/Localys).
# Requires a repo secret FORK_SYNC_TOKEN (a PAT with public_repo or repo scope).
name: Notify forks of upstream push

on:
  push:
    branches:
      - main

env:
  # Comma-separated list of target forks in "owner/repo" format
  TARGET_FORKS: "DeoTime/Localys-HOSTING"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify target forks
        env:
          TOKEN: ${{ secrets.FORK_SYNC_TOKEN }}
          TARGETS: ${{ env.TARGET_FORKS }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "Missing FORK_SYNC_TOKEN secret. Exiting."
            exit 1
          fi
          BODY=$(jq -n --arg ref "${GITHUB_REF}" --arg sha "${GITHUB_SHA}" '{event_type: "upstream_push", client_payload: {ref: $ref, sha: $sha, repository: env.GITHUB_REPOSITORY}}')
          echo "Dispatch payload: $BODY"
          IFS=',' read -ra REPOS <<< "$TARGETS"
          for repo in "${REPOS[@]}"; do
            repo=$(echo "$repo" | xargs) # trim whitespace
            echo "Dispatching to $repo"
            curl -s -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $TOKEN" \
              -d "$BODY" \
              "https://api.github.com/repos/$repo/dispatches"
            echo
          done