'use client';

import { useMemo, useState } from 'react';
import {
  BarChart, Bar, LineChart, Line, ComposedChart, PieChart, Pie, Cell, Legend,
  XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid,
} from 'recharts';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Download, FileText, SlidersHorizontal } from 'lucide-react';
import type { ItemPurchase } from '@/models/Order';
import type { BusinessReview } from '@/lib/supabase/reviews';
import {
  normalizeOrders, generateDemoOrders, filterOrders, categoriesOf, itemsOf,
  salesSummary, revenueOverTime, topItems, customerStats, ratingTrend,
  categoryBreakdown, rangeForPreset, toCSV, type DateRange,
} from '@/lib/reports';

const ORANGE = '#f97316';
/** Orange-family + grays only — keeps multi-series charts on-brand (no blue/green/yellow). */
const SLICE_COLORS = ['#f97316', '#111111', '#fdba74', '#9ca3af', '#fb923c', '#d1d5db', '#c2410c'];
type ReportKind = 'sales' | 'items' | 'customers';
type Preset = '7d' | '30d' | '90d' | 'custom';

const METRICS = [
  { key: 'revenue', label: 'Revenue' },
  { key: 'orders', label: 'Orders' },
  { key: 'aov', label: 'Avg Order Value' },
  { key: 'units', label: 'Units Sold' },
  { key: 'customers', label: 'Customers' },
] as const;
type MetricKey = (typeof METRICS)[number]['key'];

function fmtMoney(n: number) {
  return `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function downloadCSV(filename: string, csv: string) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

/** Orange/black/white brand colors as RGB tuples for jsPDF. */
const PDF_ORANGE: [number, number, number] = [249, 115, 22];
const PDF_INK: [number, number, number] = [17, 17, 17];
const PDF_MUTED: [number, number, number] = [110, 110, 110];

/**
 * Build and download a branded, multi-section PDF: header (business + title +
 * filter), a summary-cards block, and the current report's table. Respects the
 * active filters (the caller passes already-filtered data). On-brand:
 * orange table headers, black text, white background — no green/yellow.
 */
function exportPDF(opts: {
  fileName: string;
  businessName: string;
  title: string;
  filterLabel: string;
  summary: { label: string; value: string }[];
  headers: string[];
  rows: (string | number)[][];
  footer?: (string | number)[];
}) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;

  // Header
  doc.setTextColor(...PDF_INK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(opts.businessName, marginX, 48);
  doc.setFontSize(13);
  doc.setTextColor(...PDF_ORANGE);
  doc.text(opts.title, marginX, 68);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...PDF_MUTED);
  doc.text(opts.filterLabel, marginX, 84);

  // Orange divider
  doc.setDrawColor(...PDF_ORANGE);
  doc.setLineWidth(2);
  doc.line(marginX, 92, pageWidth - marginX, 92);

  // Summary cards (label / value grid)
  autoTable(doc, {
    startY: 104,
    head: [['Summary', '']],
    body: opts.summary.map((s) => [s.label, s.value]),
    theme: 'grid',
    headStyles: { fillColor: PDF_ORANGE, textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: PDF_INK },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: marginX, right: marginX },
  });

  // Main report table
  const afterSummary = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable;
  autoTable(doc, {
    startY: (afterSummary?.finalY ?? 140) + 16,
    head: [opts.headers],
    body: opts.rows.map((r) => r.map((c) => String(c ?? ''))),
    foot: opts.footer ? [opts.footer.map((c) => String(c ?? ''))] : undefined,
    theme: 'striped',
    headStyles: { fillColor: PDF_ORANGE, textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [250, 247, 245], textColor: PDF_INK, fontStyle: 'bold' },
    bodyStyles: { textColor: PDF_INK },
    alternateRowStyles: { fillColor: [250, 247, 245] },
    styles: { fontSize: 9, cellPadding: 5 },
    margin: { left: marginX, right: marginX },
  });

  // Footer note on every page
  const pageCount = doc.getNumberOfPages();
  const generated = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(`Generated by Localy Business Manager · ${generated}`, marginX, doc.internal.pageSize.getHeight() - 24);
  }

  doc.save(opts.fileName);
}

export function BusinessReports({
  orders, reviews, businessName = 'Your Business',
}: {
  orders: ItemPurchase[];
  reviews: BusinessReview[];
  businessName?: string;
}) {
  const now = useMemo(() => Date.now(), []);
  const allOrders = useMemo(() => {
    const real = normalizeOrders(orders);
    return real.length >= 5 ? real : generateDemoOrders(now);
  }, [orders, now]);
  const usingDemo = normalizeOrders(orders).length < 5;

  const [report, setReport] = useState<ReportKind>('sales');
  const [preset, setPreset] = useState<Preset>('30d');
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');
  const [category, setCategory] = useState('All');
  const [item, setItem] = useState('All');
  const [hidden, setHidden] = useState<Set<MetricKey>>(new Set());
  const [showToggles, setShowToggles] = useState(false);

  const range: DateRange = useMemo(() => {
    if (preset === 'custom' && customStart && customEnd) {
      const start = new Date(customStart); start.setHours(0, 0, 0, 0);
      const end = new Date(customEnd); end.setHours(23, 59, 59, 999);
      return start <= end ? { start, end } : rangeForPreset('30d', now);
    }
    return rangeForPreset(preset === 'custom' ? '30d' : preset, now);
  }, [preset, customStart, customEnd, now]);

  const categories = useMemo(() => categoriesOf(allOrders), [allOrders]);
  const items = useMemo(() => itemsOf(allOrders, category), [allOrders, category]);

  const filtered = useMemo(
    () => filterOrders(allOrders, range, category, item),
    [allOrders, range, category, item],
  );

  const summary = useMemo(() => salesSummary(filtered), [filtered]);
  const overTime = useMemo(() => revenueOverTime(filtered, range), [filtered, range]);
  const items5 = useMemo(() => topItems(filtered), [filtered]);
  const byCategory = useMemo(() => categoryBreakdown(filtered), [filtered]);
  const custs = useMemo(() => customerStats(filtered), [filtered]);
  const ratings = useMemo(() => ratingTrend(reviews, range), [reviews, range]);

  const rangeLabel = `${range.start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${range.end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
  const filterLabel = `${rangeLabel}${category !== 'All' ? ` · ${category}` : ''}${item !== 'All' ? ` · ${item}` : ''}`;

  const isVisible = (k: MetricKey) => !hidden.has(k);
  const toggleMetric = (k: MetricKey) =>
    setHidden((prev) => { const n = new Set(prev); n.has(k) ? n.delete(k) : n.add(k); return n; });

  const metricCards: { key: MetricKey; label: string; value: string }[] = [
    { key: 'revenue', label: 'Total Revenue', value: fmtMoney(summary.revenue) },
    { key: 'orders', label: 'Orders', value: String(summary.orders) },
    { key: 'aov', label: 'Avg Order Value', value: fmtMoney(summary.avgOrderValue) },
    { key: 'units', label: 'Units Sold', value: String(summary.units) },
    { key: 'customers', label: 'Customers', value: String(summary.uniqueCustomers) },
  ];

  /* ----- export current report (respects filters) ----- */
  const buildExport = (): { headers: string[]; rows: (string | number)[][]; footer: (string | number)[]; title: string } => {
    if (report === 'sales') {
      return {
        title: 'Sales & Revenue Report',
        headers: ['Date', 'Orders', 'Revenue'],
        rows: overTime.map((b) => [b.label, b.orders, b.revenue.toFixed(2)]),
        footer: ['Total', summary.orders, summary.revenue.toFixed(2)],
      };
    }
    if (report === 'items') {
      return {
        title: 'Top-Selling Items Report',
        headers: ['Rank', 'Item', 'Category', 'Quantity', 'Revenue', '% of Sales'],
        rows: items5.map((it) => [it.rank, it.name, it.category, it.quantity, it.revenue.toFixed(2), `${it.pctOfSales}%`]),
        footer: ['', 'Total', '', summary.units, summary.revenue.toFixed(2), '100%'],
      };
    }
    return {
      title: 'Customer & Engagement Report',
      headers: ['Customer', 'Orders', 'Revenue'],
      rows: custs.topCustomers.map((c) => [c.buyerId, c.orders, c.revenue.toFixed(2)]),
      footer: ['Total customers', custs.total, summary.revenue.toFixed(2)],
    };
  };

  const handleCSV = () => {
    const { headers, rows, title } = buildExport();
    downloadCSV(`${title.replace(/\s+/g, '-').toLowerCase()}.csv`, toCSV(headers, rows));
  };
  const handlePDF = () => {
    try {
      const { headers, rows, footer, title } = buildExport();
      const fileName = `${businessName}-${title}`.replace(/\s+/g, '-').toLowerCase() + '.pdf';
      exportPDF({
        fileName,
        businessName,
        title,
        filterLabel,
        summary: metricCards.filter((c) => isVisible(c.key)).map((c) => ({ label: c.label, value: c.value })),
        headers,
        rows,
        footer,
      });
    } catch (err) {
      console.error('PDF export failed:', err instanceof Error ? err.message : err);
    }
  };

  const REPORTS: { key: ReportKind; label: string }[] = [
    { key: 'sales', label: 'Sales / Revenue' },
    { key: 'items', label: 'Top Items' },
    { key: 'customers', label: 'Customers' },
  ];

  return (
    <div className="space-y-5">
      {/* Report selector + export */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap gap-1.5">
          {REPORTS.map((r) => (
            <button
              key={r.key}
              onClick={() => setReport(r.key)}
              className={`rounded-xl px-3.5 py-2 text-sm font-semibold transition-colors ${
                report === r.key ? 'bg-[#f97316] text-white' : 'border border-gray-200 bg-white text-gray-700 hover:bg-gray-50'
              }`}
            >
              {r.label}
            </button>
          ))}
        </div>
        <div className="flex gap-2">
          <button onClick={handleCSV} className="flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-sm font-semibold text-gray-900 hover:border-[#f97316] hover:text-[#f97316] transition-colors">
            <Download className="h-4 w-4" /> CSV
          </button>
          <button onClick={handlePDF} className="flex items-center gap-1.5 rounded-xl bg-black px-3.5 py-2 text-sm font-semibold text-white hover:opacity-90 transition-opacity">
            <FileText className="h-4 w-4" /> PDF
          </button>
        </div>
      </div>

      {usingDemo && (
        <p className="rounded-xl border border-gray-200 bg-white px-4 py-2 text-xs text-gray-600">
          Showing realistic demo data — your real orders will populate these reports automatically.
        </p>
      )}

      {/* Filters */}
      <div className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
        <div className="flex flex-wrap items-end gap-4">
          {/* Date range */}
          <div>
            <p className="mb-1.5 text-xs font-semibold text-gray-700">Date range</p>
            <div className="flex flex-wrap gap-1.5">
              {(['7d', '30d', '90d', 'custom'] as Preset[]).map((p) => (
                <button
                  key={p}
                  onClick={() => setPreset(p)}
                  className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors ${
                    preset === p ? 'bg-[#f97316] text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {p === '7d' ? 'Last 7 days' : p === '30d' ? 'Last 30 days' : p === '90d' ? 'Last 90 days' : 'Custom'}
                </button>
              ))}
            </div>
          </div>

          {preset === 'custom' && (
            <div className="flex items-end gap-2">
              <div>
                <p className="mb-1.5 text-xs font-semibold text-gray-700">From</p>
                <input type="date" aria-label="Custom range start date" value={customStart} onChange={(e) => setCustomStart(e.target.value)}
                  className="rounded-lg border border-gray-200 bg-gray-50 px-2.5 py-1.5 text-xs text-gray-900 focus:border-[#f97316] focus:outline-none" />
              </div>
              <div>
                <p className="mb-1.5 text-xs font-semibold text-gray-700">To</p>
                <input type="date" aria-label="Custom range end date" value={customEnd} onChange={(e) => setCustomEnd(e.target.value)}
                  className="rounded-lg border border-gray-200 bg-gray-50 px-2.5 py-1.5 text-xs text-gray-900 focus:border-[#f97316] focus:outline-none" />
              </div>
            </div>
          )}

          {/* Category */}
          <div>
            <p className="mb-1.5 text-xs font-semibold text-gray-700">Category</p>
            <select
              aria-label="Filter by category"
              value={category}
              onChange={(e) => { setCategory(e.target.value); setItem('All'); }}
              className="rounded-lg border border-gray-200 bg-gray-50 px-2.5 py-1.5 text-xs text-gray-900 focus:border-[#f97316] focus:outline-none"
            >
              <option value="All">All categories</option>
              {categories.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>

          {/* Item */}
          <div>
            <p className="mb-1.5 text-xs font-semibold text-gray-700">Item</p>
            <select
              aria-label="Filter by item"
              value={item}
              onChange={(e) => setItem(e.target.value)}
              className="rounded-lg border border-gray-200 bg-gray-50 px-2.5 py-1.5 text-xs text-gray-900 focus:border-[#f97316] focus:outline-none"
            >
              <option value="All">All items</option>
              {items.map((it) => <option key={it} value={it}>{it}</option>)}
            </select>
          </div>

          <button
            aria-label="Toggle which metric cards are shown"
            onClick={() => setShowToggles((s) => !s)}
            className="ml-auto flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 hover:border-[#f97316] hover:text-[#f97316] transition-colors"
          >
            <SlidersHorizontal className="h-3.5 w-3.5" /> Metrics
          </button>
        </div>

        {showToggles && (
          <div className="mt-3 flex flex-wrap gap-3 border-t border-gray-100 pt-3">
            {METRICS.map((m) => (
              <label key={m.key} className="flex items-center gap-1.5 text-xs font-medium text-gray-700">
                <input type="checkbox" checked={isVisible(m.key)} onChange={() => toggleMetric(m.key)} className="accent-[#f97316]" />
                {m.label}
              </label>
            ))}
          </div>
        )}
      </div>

      {/* Metric cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        {metricCards.filter((c) => isVisible(c.key)).map((c) => (
          <div key={c.key} className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <p className="text-[11px] font-medium text-gray-600">{c.label}</p>
            <p className="mt-1 text-xl font-bold text-gray-900">{c.value}</p>
          </div>
        ))}
      </div>

      {/* ---- SALES ---- */}
      {report === 'sales' && (
        <>
          <ChartCard title="Revenue & orders over time" subtitle={rangeLabel}>
            <ResponsiveContainer width="100%" height="100%">
              <ComposedChart data={overTime} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                <XAxis dataKey="label" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} />
                <YAxis yAxisId="rev" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v}`} />
                <YAxis yAxisId="ord" orientation="right" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} allowDecimals={false} />
                <Tooltip
                  formatter={(v: number | undefined, name) => name === 'Revenue' ? [fmtMoney(v ?? 0), 'Revenue'] : [String(v ?? 0), 'Orders']}
                  contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }}
                  cursor={{ fill: '#f97316', opacity: 0.06 }}
                />
                <Legend wrapperStyle={{ fontSize: 11 }} />
                <Bar yAxisId="ord" dataKey="orders" name="Orders" fill="#fdba74" radius={[4, 4, 0, 0]} barSize={14} />
                <Line yAxisId="rev" type="monotone" dataKey="revenue" name="Revenue" stroke={ORANGE} strokeWidth={2.5} dot={false} />
              </ComposedChart>
            </ResponsiveContainer>
          </ChartCard>

          <TableCard
            headers={['Date', 'Orders', 'Revenue']}
            rows={overTime.map((b) => [b.label, String(b.orders), fmtMoney(b.revenue)])}
            footer={['Total', String(summary.orders), fmtMoney(summary.revenue)]}
          />
        </>
      )}

      {/* ---- TOP ITEMS ---- */}
      {report === 'items' && (
        <>
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <ChartCard title="Top items by revenue" subtitle={rangeLabel}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={items5.slice(0, 8)} layout="vertical" margin={{ top: 4, right: 16, left: 8, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f3f4f6" />
                  <XAxis type="number" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v}`} />
                  <YAxis type="category" dataKey="name" width={120} tick={{ fontSize: 11, fill: '#6b7280' }} axisLine={false} tickLine={false} />
                  <Tooltip formatter={(v: number | undefined) => [fmtMoney(v ?? 0), 'Revenue']} contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} cursor={{ fill: '#f97316', opacity: 0.06 }} />
                  <Bar dataKey="revenue" fill={ORANGE} radius={[0, 6, 6, 0]} barSize={16} />
                </BarChart>
              </ResponsiveContainer>
            </ChartCard>

            <ChartCard title="Revenue share by category" subtitle={rangeLabel}>
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={byCategory} dataKey="revenue" nameKey="category" cx="50%" cy="50%" innerRadius={48} outerRadius={78} paddingAngle={2} stroke="#fff" strokeWidth={2}>
                    {byCategory.map((_, i) => <Cell key={i} fill={SLICE_COLORS[i % SLICE_COLORS.length]} />)}
                  </Pie>
                  <Tooltip formatter={(v: number | undefined, name) => [fmtMoney(v ?? 0), name as string]} contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} />
                  <Legend wrapperStyle={{ fontSize: 11 }} />
                </PieChart>
              </ResponsiveContainer>
            </ChartCard>
          </div>

          <TableCard
            headers={['#', 'Item', 'Category', 'Qty', 'Revenue', '% of Sales']}
            rows={items5.map((it) => [String(it.rank), it.name, it.category, String(it.quantity), fmtMoney(it.revenue), `${it.pctOfSales}%`])}
            footer={['', 'Total', '', String(summary.units), fmtMoney(summary.revenue), '100%']}
          />
        </>
      )}

      {/* ---- CUSTOMERS ---- */}
      {report === 'customers' && (
        <>
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <ChartCard title="New vs returning customers" subtitle={rangeLabel}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={[
                  { label: 'New', value: custs.newCustomers },
                  { label: 'Returning', value: custs.returning },
                ]} barSize={48}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                  <XAxis dataKey="label" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} allowDecimals={false} />
                  <Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} cursor={{ fill: '#f97316', opacity: 0.06 }} />
                  <Bar dataKey="value" fill={ORANGE} radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </ChartCard>

            <ChartCard title="Average rating trend" subtitle="By month">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={ratings} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                  <XAxis dataKey="label" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} />
                  <YAxis domain={[0, 5]} tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} />
                  <Tooltip formatter={(v: number | undefined) => [`${v ?? 0}`, 'Avg rating']} contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} />
                  <Line type="monotone" dataKey="rating" stroke={ORANGE} strokeWidth={2.5} dot={{ r: 3, fill: ORANGE }} />
                </LineChart>
              </ResponsiveContainer>
            </ChartCard>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <MiniStat label="Total Customers" value={String(custs.total)} />
            <MiniStat label="Returning" value={`${custs.returning} (${custs.returningPct}%)`} />
            <MiniStat label="New" value={String(custs.newCustomers)} />
            <MiniStat label="Reviews" value={String(reviews.length || ratings.reduce((s, r) => s + r.count, 0))} />
          </div>

          <ChartCard title="Top customers by revenue" subtitle={rangeLabel}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={custs.topCustomers} layout="vertical" margin={{ top: 4, right: 16, left: 8, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f3f4f6" />
                <XAxis type="number" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v}`} />
                <YAxis type="category" dataKey="buyerId" width={120} tick={{ fontSize: 11, fill: '#6b7280' }} axisLine={false} tickLine={false} />
                <Tooltip formatter={(v: number | undefined) => [fmtMoney(v ?? 0), 'Revenue']} contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} cursor={{ fill: '#f97316', opacity: 0.06 }} />
                <Bar dataKey="revenue" fill={ORANGE} radius={[0, 6, 6, 0]} barSize={16} />
              </BarChart>
            </ResponsiveContainer>
          </ChartCard>

          <TableCard
            headers={['Customer', 'Orders', 'Revenue']}
            rows={custs.topCustomers.map((c) => [c.buyerId, String(c.orders), fmtMoney(c.revenue)])}
            footer={['Total customers', String(custs.total), fmtMoney(summary.revenue)]}
          />
        </>
      )}
    </div>
  );
}

function ChartCard({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
      <div className="mb-3 flex items-center justify-between">
        <p className="text-sm font-semibold text-gray-900">{title}</p>
        {subtitle && <span className="rounded-lg bg-gray-100 px-2 py-1 text-xs text-gray-500">{subtitle}</span>}
      </div>
      <div className="h-56">{children}</div>
    </div>
  );
}

function TableCard({ headers, rows, footer }: { headers: string[]; rows: string[][]; footer?: string[] }) {
  return (
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 bg-gray-50 text-left">
              {headers.map((h, i) => (
                <th key={h} className={`px-4 py-2.5 text-xs font-semibold uppercase tracking-wide text-gray-600 ${i === 0 ? '' : 'text-right'}`}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr><td colSpan={headers.length} className="px-4 py-8 text-center text-sm text-gray-400">No data for this filter</td></tr>
            ) : rows.map((r, ri) => (
              <tr key={ri} className="border-b border-gray-50 last:border-0 hover:bg-gray-50">
                {r.map((cell, ci) => (
                  <td key={ci} className={`px-4 py-2.5 ${ci === 0 ? 'font-medium text-gray-900' : 'text-right text-gray-700'}`}>{cell}</td>
                ))}
              </tr>
            ))}
          </tbody>
          {footer && rows.length > 0 && (
            <tfoot>
              <tr className="border-t border-gray-200 bg-orange-50/50 font-bold text-gray-900">
                {footer.map((cell, ci) => (
                  <td key={ci} className={`px-4 py-2.5 ${ci === 0 ? '' : 'text-right'}`}>{cell}</td>
                ))}
              </tr>
            </tfoot>
          )}
        </table>
      </div>
    </div>
  );
}

function MiniStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 text-center shadow-sm">
      <p className="text-xl font-bold text-gray-900">{value}</p>
      <p className="mt-0.5 text-[11px] text-gray-600">{label}</p>
    </div>
  );
}
